name: Hilman Firdd Daily Commit

on:
  schedule:
    - cron: "0 */5 * * *" # Setiap 5 jam
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0 # Ambil semua commit untuk menghindari masalah push

      - name: Set Up Git
        run: |
          git config --global user.name "hilman-firdd"
          git config --global user.email "hilmanfirdaus@gmail.com"

      - name: Create or Update Commit File
        run: |
          set -e  # Berhenti jika ada error
          FILE="commit_number.md"

          if [ ! -f "$FILE" ]; then
            echo "Hello, my name is Hilman Firdd" > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE" || echo "0")
            NEXT_COUNT=$((CURRENT_COUNT + 1))
            sed -i'' -e "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
          fi

          cat "$FILE"  # Debugging: Tampilkan isi file

      - name: Commit and Push Changes
        run: |
          set -e  # Berhenti jika ada error
          git add commit_number.md
          git commit -m "Automated commit #$(grep -oP 'commit number: \K\d+' commit_number.md)"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
